version: '3'
services:
  webserver:
    build:
        context: ./web
        dockerfile: ./echo.dockerfile
    ports:
      - 8080:8080
  dbserver:
    build:
        context: ./mysql
        dockerfile: ./mysql.dockerfile
    ports:
      - 3306:3306
    hostname: dbserver